/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.54
 * Generated at: 2021-11-15 08:31:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class boardList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Jua&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("	body{\r\n");
      out.write("		background: ghostwhite;\r\n");
      out.write("		margin-left: 10%;\r\n");
      out.write("		margin-right: 10%;\r\n");
      out.write("		font-family: 'Jua', sans-serif;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	header{\r\n");
      out.write("		font-family: 'Jua', sans-serif;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	#wrap-all{\r\n");
      out.write("		min-height: 100%;\r\n");
      out.write("		position: relative;\r\n");
      out.write("	}\r\n");
      out.write("	#board_wrap{\r\n");
      out.write("		padding-bottom: 30%;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	#logo {width: 200px;}\r\n");
      out.write("	#login {text-align: right; font-size: 8px;}\r\n");
      out.write("	\r\n");
      out.write("	#searchText {\r\n");
      out.write("		text-align: right;\r\n");
      out.write("		margin-top: 10px;\r\n");
      out.write("		margin-bottom: 10px;\r\n");
      out.write("		padding: 0px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	#searchWord {\r\n");
      out.write("		border: 1px solid #00CED1;\r\n");
      out.write("		font-size: 15px;\r\n");
      out.write("		width: 300px;\r\n");
      out.write("		height: 30px;\r\n");
      out.write("	}\r\n");
      out.write("	#input {\r\n");
      out.write("		border: none;\r\n");
      out.write("		background: #00CED1;\r\n");
      out.write("		vertical-align: middle;\r\n");
      out.write("		font-family: 'Jua', sans-serif;\r\n");
      out.write("		width: 50px;\r\n");
      out.write("		height: 35px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	#topMenu {\r\n");
      out.write("		height: 30px;\r\n");
      out.write("		width: 100%;\r\n");
      out.write("		margin: 0px;\r\n");
      out.write("		padding: 0px;\r\n");
      out.write("	}\r\n");
      out.write("	#topMenu ul {\r\n");
      out.write("		margin: 0px;\r\n");
      out.write("		padding: 0px;\r\n");
      out.write("	}\r\n");
      out.write("	#topMenu ul li {\r\n");
      out.write("		list-style: none;\r\n");
      out.write("		color: white;\r\n");
      out.write("		float: left;\r\n");
      out.write("		line-height: 30px;\r\n");
      out.write("		vertical-align: middle;\r\n");
      out.write("		text-align: center;\r\n");
      out.write("	}\r\n");
      out.write("	#topMenu .menuLink {\r\n");
      out.write("		text-decoration: none;\r\n");
      out.write("		color: black;\r\n");
      out.write("		display: block;\r\n");
      out.write("		font-size: 15px;\r\n");
      out.write("		font-weight: bold;\r\n");
      out.write("	}\r\n");
      out.write("	#topMenu ul li:hover {background-color: ghostwhite;}\r\n");
      out.write("	\r\n");
      out.write("	#search {background: #AFEEEE; width: 20%;}\r\n");
      out.write("	#review {background: #7FFFD4; width: 20%;}\r\n");
      out.write("	#allview {background: #40E0D0; width: 20%;}\r\n");
      out.write("	#allbuy {background: #48D1CC; width: 20%;}\r\n");
      out.write("	#mypage {background: #00CED1; width: 20%;}\r\n");
      out.write("	\r\n");
      out.write("	.board_title{\r\n");
      out.write("		vertical-align: middle;\r\n");
      out.write("		text-align: center;\r\n");
      out.write("		border-bottom: 1px solid black;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.main_table{\r\n");
      out.write("		width:100%;\r\n");
      out.write("	}\r\n");
      out.write("	#board_table, #move_page, #search_area{\r\n");
      out.write("		text-align:center;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	#write_button{\r\n");
      out.write("		text-align: right;\r\n");
      out.write("	}\r\n");
      out.write("	#wbtn{\r\n");
      out.write("		border: none;\r\n");
      out.write("		background: #00CED1;\r\n");
      out.write("		font-family: 'Jua', sans-serif;\r\n");
      out.write("		height: 25px;\r\n");
      out.write("		border-radius: 5px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	a{\r\n");
      out.write("		color: black;\r\n");
      out.write("		text-decoration: none;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	table.main_table {\r\n");
      out.write("	    border-collapse: collapse;\r\n");
      out.write("	  	text-align: left;\r\n");
      out.write("	  	line-height: 1.5;\r\n");
      out.write("	  	font-size: 12px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	table.main_table thead th {\r\n");
      out.write("	  padding: 10px;\r\n");
      out.write("	  font-weight: bold;\r\n");
      out.write("	  border-top: 1px solid #ccc;\r\n");
      out.write("	  border-bottom: 2px solid #00CED1;\r\n");
      out.write("	  background: #AFEEEE;\r\n");
      out.write("	}\r\n");
      out.write("	table.main_table tbody th {\r\n");
      out.write("	  padding: 10px;\r\n");
      out.write("	  font-weight: bold;\r\n");
      out.write("	  vertical-align: top;\r\n");
      out.write("	  border-bottom: 1px solid #ccc;\r\n");
      out.write("	  background: #ececec;\r\n");
      out.write("	}\r\n");
      out.write("	table.main_table td {\r\n");
      out.write("	  padding: 10px;\r\n");
      out.write("	  vertical-align: top;\r\n");
      out.write("	  border-bottom: 1px solid #ccc;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	#choose{\r\n");
      out.write("		border: none;\r\n");
      out.write("		height: 25px;\r\n");
      out.write("		background: #00CED1;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	#board_search{\r\n");
      out.write("		border: 1px solid #00CED1;\r\n");
      out.write("		height: 25px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	#search_btn{\r\n");
      out.write("		border: none;\r\n");
      out.write("		background: #00CED1;\r\n");
      out.write("		font-family: 'Jua', sans-serif;\r\n");
      out.write("		height: 25px;\r\n");
      out.write("		border-radius: 5px;\r\n");
      out.write("	}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<header>\r\n");
      out.write("		<div id=\"login\">회원가입 / 로그인</div>\r\n");
      out.write("		<div>\r\n");
      out.write("			<a href=\"D:\\semi-Project\\semi-Project\\WebContent\\index.html\">\r\n");
      out.write("			<img id=\"logo\" src=\"../images/logo.png\"></a>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div id=\"searchText\">\r\n");
      out.write("			<input type=\"text\" id=\"searchWord\"><button id=\"input\">검색</button>\r\n");
      out.write("		</div>\r\n");
      out.write("		<nav id=\"topMenu\">\r\n");
      out.write("			<ul>\r\n");
      out.write("				<li id=\"search\"><a class=\"menuLink\" href=\"#\">상세검색</a></li>\r\n");
      out.write("				<li id=\"review\"><a class=\"menuLink\" href=\"board_into.html\">리뷰 게시판</a></li>\r\n");
      out.write("				<li id=\"allview\"><a class=\"menuLink\" href=\"#\">단체관람 게시판</a></li>\r\n");
      out.write("				<li id=\"allbuy\"><a class=\"menuLink\" href=\"#\">공동구매 게시판</a></li>\r\n");
      out.write("				<li id=\"mypage\"><a class=\"menuLink\" href=\"#\">공지사항</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</nav>\r\n");
      out.write("	</header>\r\n");
      out.write("	<div id=\"wrap-all\">\r\n");
      out.write("		<section id=\"board_wrap\">\r\n");
      out.write("\r\n");
      out.write("			<div class=\"board_title\">\r\n");
      out.write("				<h3>▒ 리뷰 게시판 ▒</h3>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div id=\"board_table\">\r\n");
      out.write("				<table class=\"main_table\">\r\n");
      out.write("					<thead>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<th class=\"post_num\"><span>글번호</span></th>\r\n");
      out.write("							<th class=\"post_title\">제목</th>\r\n");
      out.write("							<th class=\"post_writer\">작성자</th>\r\n");
      out.write("							<th class=\"post_date\">작성일</th>\r\n");
      out.write("							<th class=\"post_time\">작성시각</th>\r\n");
      out.write("							<th class=\"post_view\">조회수</th>\r\n");
      out.write("						</tr>\r\n");
      out.write("					</thead>\r\n");
      out.write("					<tbody>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td class=\"post_num\">공지</td>\r\n");
      out.write("							<td class=\"post_title\">공지1. 이것은 공지입니다.</td>\r\n");
      out.write("							<td class=\"post_writer\">관리자</td>\r\n");
      out.write("							<td class=\"post_date\">10.01</td>\r\n");
      out.write("							<td class=\"post_time\">17:35</td>\r\n");
      out.write("							<td class=\"post_view\">19395</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td class=\"post_num\">000011</td>\r\n");
      out.write("							<td class=\"post_title\">글제목 0. 여기는 리뷰게시판 입니다.</td>\r\n");
      out.write("							<td class=\"post_writer\">작성자9</td>\r\n");
      out.write("							<td class=\"post_date\">10.26</td>\r\n");
      out.write("							<td class=\"post_time\">13:20</td>\r\n");
      out.write("							<td class=\"post_view\">435</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td class=\"post_num\">000010</td>\r\n");
      out.write("							<td class=\"post_title\">글제목 1. 여기는 리뷰게시판 입니다.</td>\r\n");
      out.write("							<td class=\"post_writer\">작성자8</td>\r\n");
      out.write("							<td class=\"post_date\">10.25</td>\r\n");
      out.write("							<td class=\"post_time\">20:30</td>\r\n");
      out.write("							<td class=\"post_view\">6</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td class=\"post_num\">000009</td>\r\n");
      out.write("							<td class=\"post_title\">글제목 2. 여기는 리뷰게시판 입니다.</td>\r\n");
      out.write("							<td class=\"post_writer\">작성자7</td>\r\n");
      out.write("							<td class=\"post_date\">10.25</td>\r\n");
      out.write("							<td class=\"post_time\">15:30</td>\r\n");
      out.write("							<td class=\"post_view\">254</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td class=\"post_num\">000008</td>\r\n");
      out.write("							<td class=\"post_title\">글제목 3. 여기는 리뷰게시판 입니다.</td>\r\n");
      out.write("							<td class=\"post_writer\">작성자6</td>\r\n");
      out.write("							<td class=\"post_date\">10.25</td>\r\n");
      out.write("							<td class=\"post_time\">11:30</td>\r\n");
      out.write("							<td class=\"post_view\">4</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td class=\"post_num\">000007</td>\r\n");
      out.write("							<td class=\"post_title\">글제목 4. 여기는 리뷰게시판 입니다.</td>\r\n");
      out.write("							<td class=\"post_writer\">작성자5</td>\r\n");
      out.write("							<td class=\"post_date\">10.25</td>\r\n");
      out.write("							<td class=\"post_time\">06:30</td>\r\n");
      out.write("							<td class=\"post_view\">37</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td class=\"post_num\">000006</td>\r\n");
      out.write("							<td class=\"post_title\">글제목 5. 여기는 리뷰게시판 입니다.</td>\r\n");
      out.write("							<td class=\"post_writer\">작성자4</td>\r\n");
      out.write("							<td class=\"post_date\">10.25</td>\r\n");
      out.write("							<td class=\"post_time\">05:30</td>\r\n");
      out.write("							<td class=\"post_view\">120</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td class=\"post_num\">000005</td>\r\n");
      out.write("							<td class=\"post_title\">글제목 6. 여기는 리뷰게시판 입니다.</td>\r\n");
      out.write("							<td class=\"post_writer\">작성자3</td>\r\n");
      out.write("							<td class=\"post_date\">10.25</td>\r\n");
      out.write("							<td class=\"post_time\">03:30</td>\r\n");
      out.write("							<td class=\"post_view\">34</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td class=\"post_num\">000004</td>\r\n");
      out.write("							<td class=\"post_title\">글제목 7. 여기는 리뷰게시판 입니다.</td>\r\n");
      out.write("							<td class=\"post_writer\">작성자2</td>\r\n");
      out.write("							<td class=\"post_date\">10.25</td>\r\n");
      out.write("							<td class=\"post_time\">01:30</td>\r\n");
      out.write("							<td class=\"post_view\">20</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td class=\"post_num\">000003</td>\r\n");
      out.write("							<td class=\"post_title\">글제목 8. 여기는 리뷰게시판 입니다.</td>\r\n");
      out.write("							<td class=\"post_writer\">작성자1</td>\r\n");
      out.write("							<td class=\"post_date\">10.25</td>\r\n");
      out.write("							<td class=\"post_time\">00:30</td>\r\n");
      out.write("							<td class=\"post_view\">10</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td class=\"post_num\">000002</td>\r\n");
      out.write("							<td class=\"post_title\">글제목 9. 여기는 리뷰게시판 입니다.</td>\r\n");
      out.write("							<td class=\"post_writer\">작성자0</td>\r\n");
      out.write("							<td class=\"post_date\">10.25</td>\r\n");
      out.write("							<td class=\"post_time\">00:07</td>\r\n");
      out.write("							<td class=\"post_view\">43</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td class=\"post_num\">000001</td>\r\n");
      out.write("							<td class=\"post_title\">글제목 10. 여기는 리뷰게시판 입니다.</td>\r\n");
      out.write("							<td class=\"post_writer\">작성자10</td>\r\n");
      out.write("							<td class=\"post_date\">10.25</td>\r\n");
      out.write("							<td class=\"post_time\">00:01</td>\r\n");
      out.write("							<td class=\"post_view\">55</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("					</tbody>\r\n");
      out.write("				</table>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<div id=\"write_button\">\r\n");
      out.write("				<br>\r\n");
      out.write("				<button id=\"wbtn\" onclick=\"write()\">글작성</button>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div id=\"move_page\">\r\n");
      out.write("				<a href=\"#\">1</a> <a href=\"#\">2</a> <a href=\"#\">3</a> <a href=\"#\">4</a>\r\n");
      out.write("				<a href=\"#\">5</a> <a href=\"#\">6</a> <a href=\"#\">7</a> <a href=\"#\">8</a>\r\n");
      out.write("				<a href=\"#\">9</a> <a href=\"#\">10</a>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<br>\r\n");
      out.write("			<br>\r\n");
      out.write("\r\n");
      out.write("			<div id=\"search_area\">\r\n");
      out.write("				<form>\r\n");
      out.write("					<select id=\"choose\" name=\"choose\">\r\n");
      out.write("						<option value=\"1\">제목+내용</option>\r\n");
      out.write("						<option value=\"2\">제목</option>\r\n");
      out.write("						<option value=\"3\">내용</option>\r\n");
      out.write("						<option value=\"4\">작성자</option>\r\n");
      out.write("					</select> <input id=\"board_search\" type=\"text\" size=\"30\"\r\n");
      out.write("						placeholder=\"검색어를 입력하세요\"> <input id=\"search_btn\"\r\n");
      out.write("						type=\"submit\" value=\"검색\">\r\n");
      out.write("				</form>\r\n");
      out.write("			</div>\r\n");
      out.write("		</section>\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
