/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.54
 * Generated at: 2021-11-28 14:27:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.search;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import search.model.vo.Search;
import java.util.ArrayList;

public final class searchInfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("search.model.vo.Search");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
	
	Search s = (Search)request.getAttribute("search");
	ArrayList<Search> info = (ArrayList<Search>)request.getAttribute("info"); 

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("@import url('https://fonts.googleapis.com/css2?family=Jua&display=swap');\r\n");
      out.write("\r\n");
      out.write("	body{\r\n");
      out.write("		background: ghostwhite;\r\n");
      out.write("		margin-left: 10%;\r\n");
      out.write("		margin-right: 10%;\r\n");
      out.write("		font-family: 'Jua', sans-serif;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	header{\r\n");
      out.write("		font-family: 'Jua', sans-serif;\r\n");
      out.write("	}\r\n");
      out.write("	#logo {width: 200px;}\r\n");
      out.write("	#login {text-align: right; font-size: 8px;}\r\n");
      out.write("	\r\n");
      out.write("	#searchText {\r\n");
      out.write("		text-align: right;\r\n");
      out.write("		margin-top: 10px;\r\n");
      out.write("		margin-bottom: 10px;\r\n");
      out.write("		padding: 0px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	#searchWord {\r\n");
      out.write("		border: 1px solid #00CED1;\r\n");
      out.write("		font-size: 15px;\r\n");
      out.write("		width: 300px;\r\n");
      out.write("		height: 30px;\r\n");
      out.write("	}\r\n");
      out.write("	#input {\r\n");
      out.write("		border: none;\r\n");
      out.write("		background: #00CED1;\r\n");
      out.write("		vertical-align: middle;\r\n");
      out.write("		font-family: 'Jua', sans-serif;\r\n");
      out.write("		width: 50px;\r\n");
      out.write("		height: 35px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	#topMenu {\r\n");
      out.write("		height: 30px;\r\n");
      out.write("		width: 100%;\r\n");
      out.write("		margin: 0px;\r\n");
      out.write("		padding: 0px;\r\n");
      out.write("	}\r\n");
      out.write("	#topMenu ul {\r\n");
      out.write("		margin: 0px;\r\n");
      out.write("		padding: 0px;\r\n");
      out.write("	}\r\n");
      out.write("	#topMenu ul li {\r\n");
      out.write("		list-style: none;\r\n");
      out.write("		color: white;\r\n");
      out.write("		float: left;\r\n");
      out.write("		line-height: 30px;\r\n");
      out.write("		vertical-align: middle;\r\n");
      out.write("		text-align: center;\r\n");
      out.write("	}\r\n");
      out.write("	#topMenu .menuLink {\r\n");
      out.write("		text-decoration: none;\r\n");
      out.write("		color: black;\r\n");
      out.write("		display: block;\r\n");
      out.write("		font-size: 15px;\r\n");
      out.write("		font-weight: bold;\r\n");
      out.write("	}\r\n");
      out.write("	#topMenu ul li:hover {background-color: ghostwhite;}\r\n");
      out.write("	\r\n");
      out.write("	#search {background: #AFEEEE; width: 20%;}\r\n");
      out.write("	#review {background: #7FFFD4; width: 20%;}\r\n");
      out.write("	#allview {background: #40E0D0; width: 20%;}\r\n");
      out.write("	#allbuy {background: #48D1CC; width: 20%;}\r\n");
      out.write("	#mypage {background: #00CED1; width: 20%;}\r\n");
      out.write("\r\n");
      out.write("	#mainImg { margin:0 auto; }\r\n");
      out.write("	\r\n");
      out.write("	#mainImg{ margin-left: 22%;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	#conActor{background: #AFEEEE;\r\n");
      out.write("				margin-left: 10%;\r\n");
      out.write("				width: 350px;\r\n");
      out.write("	}\r\n");
      out.write("	#conGenre{ background: #AFEEEE;\r\n");
      out.write("				margin-left: 10%;\r\n");
      out.write("				width: 350px;}\r\n");
      out.write("	\r\n");
      out.write("	#conSummary{ background: #AFEEEE;\r\n");
      out.write("				margin-left: 10%;\r\n");
      out.write("				width: 350px;\r\n");
      out.write("				}\r\n");
      out.write("				\r\n");
      out.write("	#type{ \r\n");
      out.write("				width: 30%;\r\n");
      out.write("				margin-left: 3%;\r\n");
      out.write("				padding: 7px 7px 7px 0px;\r\n");
      out.write("				<!--border-radius: 10px 10px 10px 10px; -->\r\n");
      out.write("				 text-decoration:none;\r\n");
      out.write("				 font-size: 15px;\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	#conTitle{background: #AFEEEE;\r\n");
      out.write("				margin-left: 10%;\r\n");
      out.write("				width: 350px;\r\n");
      out.write("				font-size: 30px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	a{ text-decoration:none \r\n");
      out.write("	}\r\n");
      out.write("	a:visited { color:black; }\r\n");
      out.write("	\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<header>\r\n");
      out.write("		<div id=\"login\">회원가입 / 로그인</div>\r\n");
      out.write("		<div>\r\n");
      out.write("			<a href=\"D:\\semi-Project\\semi-Project\\WebContent\\index.html\"><img id=\"logo\" src=\"images/비도라이프시안.png\"></a>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div id=\"searchText\">\r\n");
      out.write("			<input type=\"text\" id=\"searchWord\"><button id=\"input\">검색</button>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		<nav id=\"topMenu\">\r\n");
      out.write("			<ul>\r\n");
      out.write("				<li id=\"search\"><a class=\"menuLink\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/search.ch'\">상세검색</a></li>\r\n");
      out.write("				<li id=\"review\"><a class=\"menuLink\"\r\n");
      out.write("					href=\"board_into.html\">리뷰 게시판</a></li>\r\n");
      out.write("				<li id=\"allview\"><a class=\"menuLink\" href=\"#\">단체관람 게시판</a></li>\r\n");
      out.write("				<li id=\"allbuy\"><a class=\"menuLink\" href=\"#\">공동구매 게시판</a></li>\r\n");
      out.write("				<li id=\"mypage\"><a class=\"menuLink\" href=\"#\">마이페이지</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</nav>\r\n");
      out.write("	</header>\r\n");
      out.write("	<br><br><br>\r\n");
      out.write("	\r\n");
      out.write("	    <div id =\"mainBox\">\r\n");
      out.write("			");
 for(int i = 0; i < info.size(); i++){ 
      out.write("\r\n");
      out.write("					");
 Search sc = info.get(i); 
      out.write("		\r\n");
      out.write("				<img class =\"Box\" id=\"mainImg\" src=\"images/");
      out.print(sc.getConPicNewName() );
      out.write("\" style=\"float: left\" width='25%' height='20%'>\r\n");
      out.write("				<div style=\"display: inline-block; width: 30%\"> \r\n");
      out.write("					<span id=\"conTitle\" style=\"display:inline-block\" >");
      out.print(sc.getConTitle() );
      out.write("</span><br><br>\r\n");
      out.write("					<span id=\"conActor\" style=\"display:inline-block\" >출연 : ");
      out.print(sc.getConActor() );
      out.write("</span>\r\n");
      out.write("					<span id=\"conGenre\" style=\"display: inline-block\">장르 : ");
      out.print(sc.getConGenre() );
      out.write("</span>\r\n");
      out.write("					<span id=\"conSummary\" style=\"display: inline-block\">줄거리 : ");
      out.print(sc.getConSummary() );
      out.write("</span><br>\r\n");
      out.write("												\r\n");
      out.write("				</div><br><br>\r\n");
      out.write("\r\n");
      out.write("				<span id=\"type\">		\r\n");
      out.write("					");
  if( sc.getConType().equals("넷플릭스")) 				{ 
      out.write("\r\n");
      out.write("					 			<a href=\"https://www.netflix.com/kr/\" class=\"button\"><img height=\"50px\" src=\"images\\netflix.png\"> </a> \r\n");
      out.write("					");
 		} else if(sc.getConType().equals("왓챠")) 		{ 
      out.write("\r\n");
      out.write("								<a href=\"https://watcha.com/\" class=\"button\"><img height=\"50px\" src=\"images\\watch.png\"></a>\r\n");
      out.write("					");
 		} else if(sc.getConType().equals("디즈니플러스"))   { 
      out.write("\r\n");
      out.write("								<a href=\"https://www.disneyplus.com/ko-kr\" class=\"button\"><img height=\"50px\" src=\"images\\disnep.jpg\"></a>\r\n");
      out.write("					");
 		} else if(sc.getConType().equals("티빙"))   		{ 
      out.write("\r\n");
      out.write("								<a href=\"https://www.disneyplus.com/ko-kr\" class=\"button\"><img height=\"50px\" src=\"images\\tving.jpg\"></a>\r\n");
      out.write("					");
 		} 												 
      out.write("\r\n");
      out.write("				</span>	\r\n");
      out.write("				\r\n");
      out.write("			");
 } 
      out.write("\r\n");
      out.write("		</div> \r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
